development:
    twilio:
      from: '+12692056408'
      sid: 'ACcbedf28d420b79c50d8acba6e98bd951'
      token: 'd09d6a6fbc0999ef7e6b56d75a890c79'
    robokassa:
      login: "homeinfo"
      secret: "W)e4'x583o"
      secret_2: "JHbH2JK42bB232b2j"
test:
    twilio:
      from: '+12692056408'
      sid: 'ACcbedf28d420b79c50d8acba6e98bd951'
      token: 'd09d6a6fbc0999ef7e6b56d75a890c79'
    robokassa:
      login: "homeinfo"
      secret: "W)e4'x583o"
      secret_2: "JHbH2JK42bB232b2j"
production:
    twilio:
      from: '+12692056408'
      sid: 'ACcbedf28d420b79c50d8acba6e98bd951'
      token: 'd09d6a6fbc0999ef7e6b56d75a890c79'
    robokassa:
      login: "homeinfo"
      secret: "W)e4'x583o"
      secret_2: "JHbH2JK42bB232b2j"

